// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.UGUI.Class
{
    using ResetCore.UGUI;
    
    
    public class TestUIView : UIView
    {
        
        private UnityEngine.UI.Image _imgTestButton;
        
        private UnityEngine.UI.Button _btnTestButton;
        
        private UnityEngine.UI.Text _txtText;
        
        public virtual UnityEngine.UI.Image imgTestButton
        {
            get
            {
                return this._imgTestButton;
            }
            set
            {
                this._imgTestButton = value;
            }
        }
        
        public virtual UnityEngine.UI.Button btnTestButton
        {
            get
            {
                return this._btnTestButton;
            }
            set
            {
                this._btnTestButton = value;
            }
        }
        
        public virtual UnityEngine.UI.Text txtText
        {
            get
            {
                return this._txtText;
            }
            set
            {
                this._txtText = value;
            }
        }
    }
}
