// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResetCore.ReAssembly.Data
{
    using UnityEngine;
    
    
    public class Test_TestComponent : ScriptableObject
    {
        
        public int testInt;
        
        public UnityEngine.GameObject go;
        
        public UnityEngine.GameObject go1;
    }
}
