//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: APC.proto
namespace Protobuf.Data
{
  [global::ProtoBuf.ProtoContract(Name=@"APCData")]
  public partial class APCData : global::ProtoBuf.IExtensible
  {
    public APCData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Content
    {
      get { return _content?? null; }
      set { _content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool ContentSpecified
    {
      get { return this._content != null; }
      set { if (value == (this._content== null)) this._content = value ? this.Content : (byte[])null; }
    }
    private bool ShouldSerializeContent() { return ContentSpecified; }
    private void ResetContent() { ContentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}