// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetPostUtil.proto

public final class NetPostUtil {
  private NetPostUtil() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegistOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string loginChannel = 1;
    boolean hasLoginChannel();
    String getLoginChannel();
    
    // optional string logoutChannel = 2;
    boolean hasLogoutChannel();
    String getLogoutChannel();
  }
  public static final class Regist extends
      com.google.protobuf.GeneratedMessage
      implements RegistOrBuilder {
    // Use Regist.newBuilder() to construct.
    private Regist(Builder builder) {
      super(builder);
    }
    private Regist(boolean noInit) {}
    
    private static final Regist defaultInstance;
    public static Regist getDefaultInstance() {
      return defaultInstance;
    }
    
    public Regist getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private static final Regist serializeInstance;
    public static Regist getSerializeInstance() {
      return serializeInstance;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetPostUtil.internal_static_Regist_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetPostUtil.internal_static_Regist_fieldAccessorTable;
    }
    
    private int bitField0_;
    public boolean hasAnyData() { 
    int val = 0;
    		val= (val| bitField0_);
    
     if(val != 0){
     return true;
    }
    else {
    return false;
    }
     }
    // optional string loginChannel = 1;
    public static final int LOGINCHANNEL_FIELD_NUMBER = 1;
    private java.lang.Object loginChannel_;
    public boolean hasLoginChannel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLoginChannel() {
      java.lang.Object ref = loginChannel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loginChannel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoginChannelBytes() {
      java.lang.Object ref = loginChannel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loginChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string logoutChannel = 2;
    public static final int LOGOUTCHANNEL_FIELD_NUMBER = 2;
    private java.lang.Object logoutChannel_;
    public boolean hasLogoutChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLogoutChannel() {
      java.lang.Object ref = logoutChannel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          logoutChannel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogoutChannelBytes() {
      java.lang.Object ref = logoutChannel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        logoutChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      loginChannel_ = "";
      logoutChannel_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginChannelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLogoutChannelBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        int strSize = com.google.protobuf.StringSizeCache.getStringSize(loginChannel_);
        size += com.google.protobuf.CodedOutputStream.computeBytesSizeWithPreCalculate(1,strSize);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        int strSize = com.google.protobuf.StringSizeCache.getStringSize(logoutChannel_);
        size += com.google.protobuf.CodedOutputStream.computeBytesSizeWithPreCalculate(2,strSize);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static NetPostUtil.Regist parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static NetPostUtil.Regist parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static NetPostUtil.Regist parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static NetPostUtil.Regist parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static NetPostUtil.Regist parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetPostUtil.Regist prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetPostUtil.RegistOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetPostUtil.internal_static_Regist_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetPostUtil.internal_static_Regist_fieldAccessorTable;
      }
      
      // Construct using NetPostUtil.Regist.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        loginChannel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        logoutChannel_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetPostUtil.Regist.getDescriptor();
      }
      
      public NetPostUtil.Regist getDefaultInstanceForType() {
        return NetPostUtil.Regist.getDefaultInstance();
      }
      
      public void serializeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        NetPostUtil.Regist result =  NetPostUtil.Regist.getSerializeInstance();
        buildInternal(result);
        if (!result.isInitialized()) {throw newUninitializedMessageException(result);  }
        result.writeTo(output);
      }
      public com.google.protobuf.ByteString serializeToByteString() throws java.io.IOException {
        NetPostUtil.Regist result =  NetPostUtil.Regist.getSerializeInstance();
        buildInternal(result);
        if (!result.isInitialized()) {     throw newUninitializedMessageException(result);  }
        return result.toByteString();
      }
      public NetPostUtil.Regist build() {
        NetPostUtil.Regist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private NetPostUtil.Regist buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        NetPostUtil.Regist result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public NetPostUtil.Regist buildPartial() {
        NetPostUtil.Regist result = new NetPostUtil.Regist(this);
        return buildInternal(result);}
      public NetPostUtil.Regist buildInternal(NetPostUtil.Regist result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginChannel_ = loginChannel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logoutChannel_ = logoutChannel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetPostUtil.Regist) {
          return mergeFrom((NetPostUtil.Regist)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(NetPostUtil.Regist other) {
        if (other == NetPostUtil.Regist.getDefaultInstance()) return this;
        if (other.hasLoginChannel()) {
          setLoginChannel(other.getLoginChannel());
        }
        if (other.hasLogoutChannel()) {
          setLogoutChannel(other.getLogoutChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              loginChannel_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              logoutChannel_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      public boolean hasAnyData() { 
      int val = 0;
      		val= (val| bitField0_);
      
       if(val != 0){
       return true;
      }
      else {
      return false;
      }
       }
      
      // optional string loginChannel = 1;
      private java.lang.Object loginChannel_ = "";
      public boolean hasLoginChannel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLoginChannel() {
        java.lang.Object ref = loginChannel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loginChannel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoginChannel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginChannel_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginChannel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginChannel_ = getDefaultInstance().getLoginChannel();
        onChanged();
        return this;
      }
      void setLoginChannel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        loginChannel_ = value;
        onChanged();
      }
      
      // optional string logoutChannel = 2;
      private java.lang.Object logoutChannel_ = "";
      public boolean hasLogoutChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLogoutChannel() {
        java.lang.Object ref = logoutChannel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          logoutChannel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLogoutChannel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        logoutChannel_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogoutChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logoutChannel_ = getDefaultInstance().getLogoutChannel();
        onChanged();
        return this;
      }
      void setLogoutChannel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        logoutChannel_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Regist)
    }
    
    static {
      defaultInstance = new Regist(true);
      defaultInstance.initFields();
      serializeInstance = new Regist(true);
      serializeInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Regist)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Regist_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Regist_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021NetPostUtil.proto\"5\n\006Regist\022\024\n\014loginCh" +
      "annel\030\001 \001(\t\022\025\n\rlogoutChannel\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Regist_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Regist_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Regist_descriptor,
              new java.lang.String[] { "LoginChannel", "LogoutChannel", },
              NetPostUtil.Regist.class,
              NetPostUtil.Regist.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
